on: push

name: Mato Grosso do Sul

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      STATE_CODE: MS
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: '/mnt'
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Disk Space
        run: |
          df -h
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Download
        run: |
          Rscript download.R ${{ env.STATE_CODE }}
      - name: Deploy Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add download/${{ env.STATE_CODE }}.csv
          git commit --allow-empty -m "Automated Update"
          git push
